import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "./ui/sidenav";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const LTS_VERSION = 'v2024.2.LTS';

    return (
        <html lang="en">
            <body className={inter.className}>

                <Script
                    src={`https://authorapi.learnosity.com/?${LTS_VERSION}`}
                    strategy="beforeInteractive"
                />
                <Script
                    src={`https://items.learnosity.com/?${LTS_VERSION}`}
                    strategy="beforeInteractive"
                />
                <Script
                    src={`https://reports.learnosity.com/?${LTS_VERSION}`}
                    strategy="beforeInteractive"
                />
                <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
                    
             
                    <div className="w-full flex-none md:w-64">
                    <p className="text-center p-1 bg-amber-200">{LTS_VERSION}</p>
                        <SideNav />
                    </div>
                    <div className="flex-grow p-6 md:overflow-y-auto md:p-12">

                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
